# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [4]:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}
dfSales = pd.DataFrame(data)


dfSales['Revenue'] = dfSales['Units_Sold'] * dfSales['Price']

totalUnits = dfSales['Units_Sold'].sum()
totalRevenue = dfSales['Revenue'].sum()
print(f"total units sold: {totalUnits}")
print(f"total revenue: {totalRevenue}")

avgUnits = dfSales['Units_Sold'].mean()
avgRevenue = dfSales['Revenue'].mean()
print(f"average units sold: {avgUnits:.2f}")
print(f"average revenue: {avgRevenue:.2f}")

total units sold: 105
total revenue: 16000
average units sold: 11.67
average revenue: 1777.78

## Grouping Data

In [ ]:
productGroup = dfSales.groupby('Product')[['Units_Sold', 'Revenue']].sum()
print("total by product:\n", productGroup)

Total by Product:
          Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [6]:
regionGroup = dfSales.groupby('Region')[['Units_Sold', 'Revenue']].mean()
print("Average by Region:\n", regionGroup)

Average by Region:
         Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [7]:
productRegionGroup = dfSales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()
print("sum by Product and Region:\n", productRegionGroup)

sum by Product and Region:
                 Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [8]:
dfSalesSortedUnits = dfSales.sort_values('Units_Sold', ascending=True)
print("Sorted by Units_Sold (ascending):\n", dfSalesSortedUnits)

Sorted by Units_Sold (ascending):
   Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [9]:
dfSalesSortedRevenue = dfSales.sort_values('Revenue', ascending=False)
print("Sorted by Revenue (descending):\n", dfSalesSortedRevenue)

Sorted by Revenue (descending):
   Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [10]:
dfSales['Revenue_Rank'] = dfSales['Revenue'].rank(ascending=False, method='dense').astype(int)
dfSales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000             4
1       B  South          15    200     3000             1
2       C   East          20    150     3000             1
3       A   West           5    100      500             5
4       B  North          10    200     2000             3
5       C  South          15    150     2250             2
6       A   East          10    100     1000             4
7       B   West           5    200     1000             4
8       C  North          15    150     2250             2

In [11]:
# I actually really like that

## Merging DataFrames

In [12]:
productData = {'Product': ['A', 'B', 'C'],
               'Category': ['Electronics', 'Furniture', 'Appliances']}
dfProducts = pd.DataFrame(productData)

In [13]:
dfProducts

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [14]:
dfMerged = pd.merge(dfSales, dfProducts, on='Product')
dfMerged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000             4  Electronics
1       B  South          15    200     3000             1    Furniture
2       C   East          20    150     3000             1   Appliances
3       A   West           5    100      500             5  Electronics
4       B  North          10    200     2000             3    Furniture
5       C  South          15    150     2250             2   Appliances
6       A   East          10    100     1000             4  Electronics
7       B   West           5    200     1000             4    Furniture
8       C  North          15    150     2250             2   Appliances

In [15]:
#sql...!?

In [16]:
categoryRevenue = dfMerged.groupby('Category')['Revenue'].sum()
print("Total Revenue by Category:\n", categoryRevenue)

Total Revenue by Category:
 Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64